swagger: "2.0"
info:
  version: 1.0.0
  title: "ass_my"
  description: Managing and monitoring assignments and exams
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: tranquil-falls-46415.herokuapp.com
basePath: /
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /assignments:
    get:
      description: Ottiene assignments
      operationId: getAssignments
      parameters:
        - name: taskid
          in: query
          description: id dell'assignment
          required: false
          type: string
        - name: workerid
          in: query
          description: uuid del worker
          required: false
          type: string
      responses:
        200:
          description: lista degli assignments consegnati
          schema:
            type: array
            items:
              $ref: '#/definitions/Assignment'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Fa l'upload di un nuovo assignment
      operationId: addAssignment
      parameters:
        - name: assignment
          in: body
          description: new assignment
          required: true
          schema:
            $ref: '#/definitions/NewAssignment'
      responses:
        200:
          description: assignment created response
          schema:
            $ref: '#/definitions/Assignment'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /assignments/{id}:
    get:
      description: Ritorna uno specifico assignment cercandolo per l'id
      operationId: findby assignment id
      parameters:
        - name: id
          in: path
          description: ID of assignment to fetch
          required: true
          type: string
          x-example: 'some-example'
      responses:
        200:
          description: pet response
          schema:
            $ref: '#/definitions/Assignment'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    put:
      description: fa l'update di un assignment o ne crea uno se non esiste
      operationId: udpdate assignment
      parameters:
        - name: id
          in: path
          description: ID of assignment to edit or create
          required: true
          type: string
          x-example: 'some-example'
        - name: assignment
          in: body
          description: assignment
          required: true
          schema:
            $ref: '#/definitions/Assignment'
      responses:
        202:
          description: assignment update response
          schema:
            $ref: '#/definitions/Assignment'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single assignment based on the ID supplied
      operationId: deleteAssignment
      parameters:
        - name: id
          in: path
          description: ID of assignment to delete
          required: true
          type: string
          x-eample: 'sass-89'
      responses:
        204:
          description: assignment deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  Assignment:
    allOf:
      - $ref: '#/definitions/NewAssignment'
      - required:
        - assignmentID
        properties:
          assignmentID:
            type: string
          ipAddres:
            type: string
            format: ipv6
          dateUpdated:
            type: string
            format: date-time
  NewAssignment:
    required:
      - workerID
      - taskID
      - assignmentResult
    properties:
      workerID:
        type: string
      taskID:
        type: string
      assignmentResult:
        type: object
        
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string